# Generated by Django 5.2.5 on 2025-11-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_storagesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagesettings",
            name="storage_limit_mb",
            field=models.PositiveIntegerField(
                default=2048,
                help_text="Total storage limit for this account in megabytes.",
            ),
        ),
    ]
