# Generated by Django 5.2.5 on 2025-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_storagesettings_storage_limit_mb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
