# Generated by Django 5.2.5 on 2025-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_alter_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="original_name",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
