# Generated by Django 5.2.5 on 2025-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_alter_file_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(default=0),
        ),
    ]
