# Generated by Django 5.2.5 on 2025-11-28 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_alter_file_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="original_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                fields=("owner", "original_name"), name="unique_owner_originalname"
            ),
        ),
    ]
