version: '3.9'

networks:
  app_net:
    driver: bridge
    external: true
  web_net:
    driver: bridge
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_ENDPOINT}
      MINIO_BROWSER_REDIRECT_URL: https://minio.${DOMAIN_ADDRESS}
    volumes:
      - minio_data:/data
    networks:
      - app_net
      - web_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.minio.entrypoints=http"
      - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.minio.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.minio-secure.entrypoints=https"
      - "traefik.http.routers.minio-secure.rule=Host(`minio.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.minio-secure.tls=true"
      - "traefik.http.routers.minio-secure.tls.options=default"
      - "traefik.http.routers.minio-secure.tls.certresolver=mycert"
      - "traefik.http.routers.minio-secure.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-api.entrypoints=http"
      - "traefik.http.routers.minio-api.rule=Host(`api.minio.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.minio-api.middlewares=https-redirect"
      - "traefik.http.routers.minio-api-secure.entrypoints=https"
      - "traefik.http.routers.minio-api-secure.rule=Host(`api.minio.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.minio-api-secure.tls=true"
      - "traefik.http.routers.minio-api-secure.tls.options=default"
      - "traefik.http.routers.minio-api-secure.tls.certresolver=mycert"
      - "traefik.http.routers.minio-api-secure.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

  pg_db:
    image: postgres:15
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    # ports:
    #   - "8080:80"
    depends_on:
      - pg_db
    networks:
      - app_net
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      # HTTP router → Redirect to HTTPS
      - "traefik.http.routers.pgadmin-insecure.entrypoints=http"
      - "traefik.http.routers.pgadmin-insecure.rule=Host(`pgadmin.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.pgadmin-insecure.middlewares=https-redirect"
      # Redirect middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # HTTPS router
      - "traefik.http.routers.pgadmin-secure.entrypoints=https"
      - "traefik.http.routers.pgadmin-secure.rule=Host(`pgadmin.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.pgadmin-secure.tls.certresolver=mycert"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"


  mqtt:
    image: emqx/emqx:5.10.0
    container_name: mqtt
    hostname: mqtt
    restart: always
    environment:
      EMQX_NAME: ${EMQX_NAME}
      EMQX_NODE__NAME: ${EMQX_NODE__NAME}
      EMQX_NODE__COOKIE: ${EMQX_NODE__COOKIE}
      EMQX_DASHBOARD__DEFAULT_USERNAME: ${EMQX_DASHBOARD__DEFAULT_USERNAME}
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD__DEFAULT_PASSWORD}

      # --- JWT Auth for Devices ---
      EMQX_AUTHENTICATION__1__ENABLE: true
      EMQX_AUTHENTICATION__1__MECHANISM: jwt
      EMQX_AUTHENTICATION__1__USE_JWKS: false
      EMQX_AUTHENTICATION__1__FROM: username
      EMQX_AUTHENTICATION__1__ALGORITHM: hmac-based
      EMQX_AUTHENTICATION__1__SECRET: ${DJANGO_SECRET_KEY}
      EMQX_AUTHENTICATION__1__SECRET_BASE64_ENCODED: false
      EMQX_AUTHENTICATION__1__DISCONNECT_AFTER_EXPIRE: true
      EMQX_AUTHENTICATION__1__VERIFY_CLAIMS__exp: required

      # --- Username/Password Auth for Worker ---
      EMQX_AUTHENTICATION__2__ENABLE: true
      EMQX_AUTHENTICATION__2__MECHANISM: password_based
      EMQX_AUTHENTICATION__2__BACKEND: built_in_database
      EMQX_AUTHENTICATION__2__USER_ID_TYPE: username
      # --- API key for Worker user nad password creation ---
      EMQX_API_KEY__BOOTSTRAP_FILE: "/opt/emqx/etc/api_keys.conf"
    volumes:
      - emqx_data:/opt/emqx/data
      - ./emqx/api_keys.conf:/opt/emqx/etc/api_keys.conf
    # ports:
    #   - "1883:1883"              # open to the outside world for agents
    #   - "18083:18083"            # Dashboard
    networks:
      - app_net
      - web_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      # HTTP router → HTTPS redirect
      - "traefik.http.routers.mqtt-insecure.entrypoints=http"
      - "traefik.http.routers.mqtt-insecure.rule=Host(`mqtt.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.mqtt-insecure.middlewares=https-redirect"
      # Redirect middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # HTTPS router
      - "traefik.http.routers.mqtt-secure.entrypoints=https"
      - "traefik.http.routers.mqtt-secure.rule=Host(`mqtt.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.mqtt-secure.tls.certresolver=mycert"
      - "traefik.http.services.mqtt.loadbalancer.server.port=18083"
      
      # TCP router (SNI) using passthrough so EMQX keeps TLS certs/handshake
      - "traefik.tcp.routers.mqtt-router.entrypoints=mqtt"
      - "traefik.tcp.routers.mqtt-router.rule=HostSNI(`mqtt.broker.${DOMAIN_ADDRESS}`)"
      - "traefik.tcp.routers.mqtt-router.tls.certresolver=mycert"
      # service points to container's TLS port
      - "traefik.tcp.services.mqtt-service.loadbalancer.server.port=1883"

  mqtt_setup:
    image: curlimages/curl:8.16.0
    container_name: mqtt_setup
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    volumes:
      - ./emqx_init/init_mqtt.bash:/init_mqtt.sh
    command: ["/init_mqtt.sh"]
    networks:
      - app_net
    
  mongodb:
    image: mongo:4.4
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongos", "-u", "${MONGO_INITDB_ROOT_USERNAME}", "-p", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
      start_interval: 5s
    # ports:
    #   - "27017:27017"
    networks:
      - app_net
  
  mongo_express:
    image: mongo-express:1
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    # ports:
    #   - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - app_net
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      # HTTP router → HTTPS redirect
      - "traefik.http.routers.mongoex-insecure.entrypoints=http"
      - "traefik.http.routers.mongoex-insecure.rule=Host(`mongoex.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.mongoex-insecure.middlewares=https-redirect"
      # Redirect middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # HTTPS router
      - "traefik.http.routers.mongoex-secure.entrypoints=https"
      - "traefik.http.routers.mongoex-secure.rule=Host(`mongoex.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.mongoex-secure.tls.certresolver=mycert"
      - "traefik.http.services.mongoex.loadbalancer.server.port=8081"
  
  django_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            python manage.py seed_data &&
            python manage.py create_admin &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      pg_db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mqtt:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: config.production
      POSTGRES_HOST: pg_db
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin"
      LOGS_COLLECTION: device_logs
      MQTT_HOST: mqtt
    # ports:
    #   - "8000:8000"
    networks:
      - web_net
      - app_net
    volumes:
      - django_logs:/var/log/django
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"

      # HTTP router → HTTPS redirect
      - "traefik.http.routers.django-insecure.entrypoints=http"
      - "traefik.http.routers.django-insecure.rule=Host(`web.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.django-insecure.middlewares=https-redirect"

      # Redirect middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

      # HTTPS router
      - "traefik.http.routers.django-secure.entrypoints=https"
      - "traefik.http.routers.django-secure.rule=Host(`web.${DOMAIN_ADDRESS}`)"
      - "traefik.http.routers.django-secure.tls.certresolver=mycert"
      - "traefik.http.services.django.loadbalancer.server.port=8000"


  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    # ports:
    #   - "6379:6379"
    networks:
      - app_net

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A config worker --loglevel=info --concurrency=2
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.production
      POSTGRES_HOST: pg_db
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin"
      LOGS_COLLECTION: device_logs
      MQTT_HOST: mqtt
    restart: always
    networks:
      - app_net
      
  django_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_worker
    command: >
      sh -c "python manage.py mqtt_worker"
    depends_on:
      mongodb:
        condition: service_healthy
      mqtt:
        condition: service_started
      redis:
        condition: service_healthy
      mqtt_setup:
        condition: service_completed_successfully
    environment:
      DJANGO_SETTINGS_MODULE: config.production
      POSTGRES_HOST: pg_db
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin"
      LOGS_COLLECTION: device_logs
      MQTT_HOST: mqtt
    restart: always
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_net


volumes:
  postgres_data:
  mongo_data:
  emqx_data:
  minio_data:
  django_logs: