# Generated by Django 5.2.5 on 2025-09-20 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "device_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("android_id", models.CharField(max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=100, unique=True)),
                ("imeis", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Device",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "Account",
            },
        ),
    ]
