# Generated by Django 5.2.5 on 2025-10-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_account_groups_account_is_active_account_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
