# Generated by Django 5.2.5 on 2025-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_account_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bucket_created",
            field=models.BooleanField(default=False),
        ),
    ]
