# Generated by Django 5.2.5 on 2026-04-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_department_device_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="android_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
