# Generated by Django 5.2.5 on 2025-09-28 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "action_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "ActionType",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "module_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Module",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "trigger_kind_id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Never Trigger"),
                            (2, "One Time Trigger"),
                            (3, "Always Trigger"),
                            (4, "Regex Trigger"),
                            (5, "Interval Trigger"),
                            (6, "Exact Time Trigger"),
                        ]
                    ),
                ),
                ("regex", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("interval_time", models.DurationField(blank=True, null=True)),
                ("exact_time", models.DateTimeField(blank=True, null=True)),
                (
                    "action_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("input", models.JSONField()),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="policies.actiontype",
                    ),
                ),
            ],
            options={
                "db_table": "Action",
            },
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("READ", "Read"),
                            ("READ_ALL", "Read All"),
                        ],
                        default="CREATE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("ACK", "Acknowledged"),
                            ("FAILED", "Failed"),
                            ("APPLIED", "Applied"),
                            ("CREATED", "Created"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "mqtt_message_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("response", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Use for device-level commands (e.g. READ_ALL). If left empty, device is derived from policy_device.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "Command",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DevicePolicySnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_id", models.UUIDField(blank=True, null=True)),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="policies.command",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_snapshots",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "DevicePolicySnapshot",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ModuleField",
            fields=[
                (
                    "field_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="policies.module",
                    ),
                ),
            ],
            options={
                "db_table": "ModuleField",
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "trigger_kind_id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Never Trigger"),
                            (2, "One Time Trigger"),
                            (3, "Always Trigger"),
                            (4, "Regex Trigger"),
                            (5, "Interval Trigger"),
                            (6, "Exact Time Trigger"),
                        ]
                    ),
                ),
                ("regex", models.CharField(blank=True, max_length=200, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("interval_time", models.DurationField(blank=True, null=True)),
                ("exact_time", models.DateTimeField(blank=True, null=True)),
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "actions",
                    models.ManyToManyField(
                        related_name="policies", to="policies.action"
                    ),
                ),
                (
                    "module_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="policies.modulefield",
                    ),
                ),
            ],
            options={
                "db_table": "Policy",
            },
        ),
        migrations.CreateModel(
            name="PolicyDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_devices",
                        to="devices.device",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_devices",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "db_table": "PolicyDevice",
                "unique_together": {("policy", "device")},
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="devices",
            field=models.ManyToManyField(
                related_name="policies",
                through="policies.PolicyDevice",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="command",
            name="policy_device",
            field=models.ForeignKey(
                blank=True,
                help_text="The PolicyDevice this command applies to. Leave empty for device-level commands (e.g. READ_ALL).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="policies.policydevice",
            ),
        ),
    ]
