# Generated by Django 5.2.5 on 2025-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="action",
            name="trigger_kind_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "One Time Trigger"),
                    (2, "Always Trigger"),
                    (3, "Regex Trigger"),
                    (4, "Interval Trigger"),
                    (5, "Exact Time Trigger"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="actions",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="policies", to="policies.action"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="trigger_kind_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "One Time Trigger"),
                    (2, "Always Trigger"),
                    (3, "Regex Trigger"),
                    (4, "Interval Trigger"),
                    (5, "Exact Time Trigger"),
                ]
            ),
        ),
    ]
