# Generated by Django 5.2.5 on 2025-10-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_remove_action_start_time_remove_policy_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="trigger_kind_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "OneTime"),
                    (2, "Always"),
                    (3, "Regex"),
                    (4, "Interval"),
                    (5, "ExactTime"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="trigger_kind_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "OneTime"),
                    (2, "Always"),
                    (3, "Regex"),
                    (4, "Interval"),
                    (5, "ExactTime"),
                ]
            ),
        ),
    ]
