# Generated by Django 5.2.5 on 2025-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("policies", "0003_alter_action_trigger_kind_id_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="command",
            index=models.Index(
                fields=["policy_device", "created_at"],
                name="Command_policy__379f85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="command",
            index=models.Index(
                fields=["policy_device", "command_type", "status", "created_at"],
                name="Command_policy__bd35c7_idx",
            ),
        ),
    ]
