# Generated by Django 5.2.5 on 2025-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_command_command_policy__379f85_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontype",
            name="example_input",
            field=models.JSONField(
                blank=True,
                help_text="An example JSON object for this action type. Admins can use this as a starting point.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actiontype",
            name="input_schema",
            field=models.JSONField(
                blank=True,
                help_text="JSON Schema describing the expected Action.input structure.",
                null=True,
            ),
        ),
    ]
