# Generated by Django 5.2.5 on 2025-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0005_actiontype_example_input_actiontype_input_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
