# Generated by Django 5.2.5 on 2025-10-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0006_alter_action_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name": "Policy", "verbose_name_plural": "Policies"},
        ),
    ]
