# Generated by Django 5.2.5 on 2026-01-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0007_alter_policy_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="input",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
