# Generated by Django 5.2.5 on 2026-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_department_device_department"),
        ("policies", "0008_alter_action_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="policies", to="devices.department"
            ),
        ),
    ]
