# Generated by Django 5.2.5 on 2026-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0009_policy_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="is_deletable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="action",
            name="is_main_action",
            field=models.BooleanField(default=False),
        ),
    ]
