# Generated by Django 5.2.5 on 2026-03-01 15:20

import django.db.models.deletion
import policies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_department_device_department"),
        ("policies", "0010_action_is_deletable_action_is_main_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("READ", "Read"),
                    ("READ_ALL", "Read All"),
                    ("DELETE_ALL", "Delete All"),
                ],
                default="CREATE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Use for device-level commands (e.g. READ_ALL/DELETE_ALL). If left empty, device is derived from policy_device.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="devices.device",
            ),
        ),
        migrations.AlterField(
            model_name="command",
            name="policy_device",
            field=models.ForeignKey(
                blank=True,
                help_text="The PolicyDevice this command applies to. Leave empty for device-level commands (e.g. READ_ALL/DELETE_ALL).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commands",
                to="policies.policydevice",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="expiration_date",
            field=models.DateTimeField(
                default=policies.models.default_policy_expiration_date
            ),
        ),
    ]
