# Generated by Django 5.2.5 on 2026-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0011_alter_command_command_type_alter_command_device_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushNotificationLauncher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Notification",
                "verbose_name_plural": "Push Notifications",
                "managed": False,
            },
        ),
    ]
